var nameList = [
    "Aadrika",
    
  "Kavya",
  "Ketan",
  "Khushi",
  "Komal",
  "Krish",
  "Krishna",
  "Kriti",
  "Kunal",
  "Kush",
  "Kusum",
  "Lakshmi",
  "Lalita",
  "Leena",
  "Madhav",
  "Madhuri",
  "Mahesh",
  "Maithili",
  "Manish",
  "Aarav",
  "Aashi",
  "Aditi",
  "Advait",
  "Aishwarya",
  "Akanksha",
  "Akhil",
  "Alok",
  "Amaira",
  "Ameya",
  "Amisha",
  "Ananya",
  "Anika",
  "Aniket",
  "Anisha",
  "Anjali",
  "Ansh",
  "Anshul",
  "Aradhya",
  "Aravind",
  "Arjun",
  "Arun",
  "Arushi",
  "Aryan",
  "Arya",
  "Aryaman",
  "Asha",
  "Ashish",
  "Atharva",
  "Avani",
  "Avinash",
  "Ayush",
  "Bhargav",
  "Bhumika",
  "Chaitanya",
  "Chandni",
  "Chetan",
  "Darsh",
  "Deepak",
  "Devanshi",
  "Devika",
  "Dhruv",
  "Divya",
  "Drishti",
  "Ekta",
  "Esha",
  "Firoz",
  "Gaurav",
  "Gayatri",
  "Geeta",
  "Girish",
  "Gopal",
  "Hansika",
  "Harsh",
  "Himanshu",
  "Ishita",
  "Ishaan",
  "Ishwar",
  "Jagdish",
  "Janhvi",
  "Jatin",
  "Jhanvi",
  "Jigar",
  "Jignesh",
  "Juhi",
  "Jyoti",
  "Kabir",
  "Kajal",
  "Kalyani",
  "Kanika",
  "Kartik",
  "Kashish",
  "Manoj",
  "Manvi",
  "Mehul",
  "Mihir",
  "Mira",
  "Mohit",
  "Mukesh",
  "Muskan",
  "Naksh",
  "Namrata",
  "Neha",
  "Nikita",
  "Nikunj",
  "Nilesh",
  "Nirav",
  "Nisha",
  "Nishant",
  "Nitin",
  "Nitya",
  "Palak",
  "Pallavi",
  "Parth",
  "Parul",
  "Pooja",
  "Prajakta",
  "Pranav",
  "Pratik",
  "Pratima",
  "Priya",
  "Priti",
  "Puneet",
  "Purvi",
  "Raghav",
  "Rahul",
  "Raj",
  "Rajat",
  "Rajeev",
  "Rajesh",
  "Rakhi",
  "Rakshit",
  "Samrat",
  "Samridh",
  "Sanaya",
  "Sanchit",
  "Sandeep",
  "Sandesh",
  "Sangita",
  "Sanjeev",
  "Sanjiv",
  "Sanjana",
  "Sanjaya",
  "Sanket",
  "Santosh",
  "Sanyog",
  "Sarika",
  "Sarita",
  "Sarthak",
  "Sasha",
  "Saskia",
  "Sathya",
  "Savita",
  "Sayali",
  "Seema",
  "Siddhant",
  "Siddharth",
  "Siddhi",
  "Simran",
  "Sneha",
  "Soham",
  "Sohini",
  "Sonali",
  "Sonia",
  "Sonika",
  "Srishti",
  "Srujan",
  "Subhash",
  "Subodh",
  "Sudarshan",
  "Sudeep",
  "Sudha",
  "Sujata",
  "Sukanya",
  "Suman",
  "Sumit",
  "Sunita",
  "Supriya",
  "Suraj",
  "Surekha",
  "Suruchi",
  "Surya",
  "Sushant",
  "Sushmita",
  "Swami",
  "Swara",
  "Swarnim",
  "Swati",
  "Sweta",
  "Tahira",
  "Tanay",
  "Tanvi",
  "Tarun",
  "Tina",
  "Tushar",
  "Uday",
  "Ujjwal",
  "Uma",
  "Umang",
  "Upendra",
  "Urvashi",
  "Usha",
  "Vaibhav",
  "Vandana",
  "Vanita",
  "Varun",
  "Vedant",
  "Veena",
  "Veer",
  "Vidhi",
  "Vidya",
  "Vijay",
  "Vikas",
  "Vikram",
  "Vinay",
  "Vineet",
  "Vinita",
  "Vipul",
  "Vishal",
  "Vishnu",
  "Vivek",
  "Yash",
  "Yashasvi",
  "Yashika",
  "Yashwant",
    
];

export function generateRandomName() {
   return nameList[Math.floor( Math.random() * nameList.length )];
};


            // this create random id like token 
// function generateRandomText(length) {
//     let result = '';
//     const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
//     const charactersLength = characters.length;
//     let counter = 0;
//     while (counter < length) {
//       result += characters.charAt(Math.floor(Math.random() * charactersLength));
//       counter += 1;
//     }
//     return result;
// }

    //   this gives meaningfull random message
export function generateRandomMessage(length) {
    const messages = [
      "Hello, how are you?",
      "How's your day going?",
      "What's up?",
      "Hey there!",
      "Good morning!",
      "Good afternoon!",
      "Good evening!",
      "Hey, how's it going?",
"What's on your mind?",
"How was your weekend?",
"Hope you're having ",
"What have you been up to?",
"Good to see you!",
"How's work/school going?",
"Nice weather today?",
"exciting going  life?",
"How's the family?",
"What are your pln?",
"What's your favorite hobby?",
"vacations planned?",
"been working on?",
"Do you have any pets?",
"you've read recently?",
"movie or TV show?",
"for the weekend?",
"your commute today?",
"type of cuisine?",
"restaurants lately?",
"physical activity?",
"Do you prefer the city or ",
"most thing that's ha",
"How do you like to relax",
"favorite type of music?",
"any favorite pod?",
"How do you stay motivated ",
"favorite type of dessert?",
"hidden talents or skills?",
"most adventurous?",
"spend your weekends?",
"What's the best advice",
"goals for the next year?",
"How do you handle stress?",
"grateful for today?",
"thing about yourself?",
"looking forward to?",
"impact on the world?",
"you've experienced?",
"favorite mantras?",
"you're proud of?",
"always wanted to try?",
"How do you define success?",
      "What's new?",
      "How's everything?",
      "Nice to meet you!",
      "What brings you here?",
      "How can I assist you?",
      "can help you with?",
      "What are you up to?",
      "Long time no see!",
      "How have you been?",
      "It's good to see you again!",
      "Welcome back!",
      "Thanks for reaching out!",
      "I'm glad you're here!"
    ];
    const randomMessage = messages[Math.floor(Math.random() * messages.length)];
    // const randomString = generateRandomText(length);
    return `${randomMessage}`;
  }